dependencies: 
  tink_cli: "0.5.1"
  haxelib: ""
  hx3compat: "1.0.3"
  hxp: "1.2.1"
  yaml: "2.0.1"
# These aren't included with haxelib, but included in haxe/lime
devDependencies: {}
haxelib: 
  name: silk 
  url: "https://lib.haxe.org/documentation/"
  license: GPL
  tags: 
    - haxelib
    - core
  description: "A neat little wrapper around haxelib."
  classPath: src
  version: "0.0.1"
  releasenote: initial release
  contributors: 
    - BulbyVR
haxe: 
  classPath: src
  hxml: 
    build: |
      --main Silk
      --neko run.n
  



